apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}-np
  namespace: {{ .Values.global.namespace }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
    component: master
  {{- if or .Values.service.annotations .Values.metrics.service.annotations }}
  annotations:
  {{- if .Values.service.annotations }}
  {{- include "mysql.tplValue" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.metrics.service.annotations }}
  {{- include "mysql.tplValue" ( dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    nodePort: 31306
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: metrics
    nodePort: 31307
    port: 9104
    protocol: TCP
    targetPort: metrics
  selector: {{- include "mysql.matchLabels" . | nindent 4 }}
    component: master
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
