{{- if .Values.master.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.master.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
    component: master
data:
  my.cnf: |-
{{ .Values.master.config | indent 4 }}
{{- end -}}
