apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tsf-mysql-master
  labels:
    pv-tsf-mysql-master: enabled
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/tsf/tsf/tsf-mysql-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: tsf.product.alauda.io/tsf-node1
          operator: In
          values:
          - enabled
