apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-tsf-mysql-master-0
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi
  selector:
    matchLabels:
      pv-tsf-mysql-master: enabled
