apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsf-region-tsf-template
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.template.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tsf-region
      app.kubernetes.io/instance: tsf-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tsf-region
        app.kubernetes.io/instance: tsf-template
    spec:
    {{- with .Values.template.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostNetwork: true
      serviceAccountName: tsf-sa
      containers:
        - name: tsf-template
          image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.template.repository }}:{{ .Values.global.images.template.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          env:
          - name: TSF_NODE1
            value: "{{ .Values.global.node_list.TSF_NODE1 }}"
          - name: TSF_NODE2
            value: "{{ .Values.global.node_list.TSF_NODE2 }}"
          - name: TSF_NODE3
            value: "{{ .Values.global.node_list.TSF_NODE3 }}"
          - name: SYSTEMD_IGNORE_CHROOT
            value: "1"
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          volumeMounts:
          - mountPath: "{{ .Values.global.volumes_root_hostpath.hostPath.path }}"
            name: "{{ .Values.global.volumes_root_hostpath.name }}"
            readOnly: false
          - mountPath: "{{ .Values.global.volumes_data_hostpath.hostPath.path }}"
            name: "{{ .Values.global.volumes_data_hostpath.name }}"
            readOnly: false
          - mountPath: "{{ .Values.global.volumes_fscgroup_hostpath.hostPath.path }}"
            name: "{{ .Values.global.volumes_fscgroup_hostpath.name }}"
            readOnly: true
          ports:
            - name: http
              containerPort: 24000 
              protocol: TCP
         # livenessProbe:
         #   failureThreshold: 2
         #   httpGet:
         #     path: /health
         #     port: 24000
         #     scheme: HTTP
         #   initialDelaySeconds: 100
         #   periodSeconds: 2
         #   successThreshold: 1
         #   timeoutSeconds: 15
          readinessProbe:
            httpGet:
              port: 24000
              path: /health
            initialDelaySeconds: 45
            periodSeconds: 15
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.template.resources | nindent 12 }}
      volumes:
      - name: "{{ .Values.global.volumes_root_hostpath.name }}"
        hostPath:
          path: "{{ .Values.global.volumes_root_hostpath.hostPath.path }}"
          type: DirectoryOrCreate
      - name: "{{ .Values.global.volumes_data_hostpath.name }}"
        hostPath:
          path: "{{ .Values.global.volumes_data_hostpath.hostPath.path }}"
          type: DirectoryOrCreate
      - name: "{{ .Values.global.volumes_fscgroup_hostpath.name }}"
        hostPath:
          path: "{{ .Values.global.volumes_fscgroup_hostpath.hostPath.path }}"
          type: DirectoryOrCreate
      {{- with .Values.template.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.template.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.template.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
