FROM docker.io/centos:7.6.1810
USER root
COPY tsf.repo /etc/yum.repos.d/
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
RUN yum install crontabs  net-tools -y
RUN  yum -y install kde-l10n-Chinese telnet && \
    yum -y install unzip glibc-common net-tools rsyslog vixie-cron crontabs &&\
    yum clean all &&\
    localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
RUN yum --disablerepo="*" --enablerepo=tsf -y install mysql-community-server  mysql-utilities mysql-connector-python-2.0.4
RUN yum install crontabs net-tools -y
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
RUN echo '*/1 * * * * /usr/bin/start-tsf.sh' >>/var/spool/cron/root
ADD tsf-mysql /opt/tsf-mysql
#COPY init.sh /root
#ADD init.sh.bak /opt
ADD start-tsf.sh /usr/bin/start-tsf.sh
COPY root /var/spool/cron/
ENTRYPOINT  ["/usr/sbin/init"]
#COPY init.sh /root
#ENV command="bash /root/tsf/common/tsf-storage/tsf-mysql/bin/install.sh  192.168.16.42 192.168.16.41,192.168.16.42  && bash /root/tsf/common/tsf-storage/tsf-mysql/bin/postProcess.sh 192.168.16.42 192.168.16.41,192.168.16.42 "
#CMD bash /root/init.sh $parameter

