FROM docker.io/centos:7.6.1810
COPY tsf.repo /etc/yum.repos.d/
RUN yum --disablerepo="*" --enablerepo=tsf -y install mysql-community-server  mysql-utilities mysql-connector-python-2.0.4
RUN yum install crontabs net-tools -y
ADD tsf-mysql /opt/tsf-mysql
COPY init.sh /root
COPY start-init.sh /root
COPY root /var/spool/cron/
#COPY init.sh /root
ENV command="bash /root/tsf/common/tsf-storage/tsf-mysql/bin/install.sh  192.168.16.42 192.168.16.41,192.168.16.42  && bash /root/tsf/common/tsf-storage/tsf-mysql/bin/postProcess.sh 192.168.16.42 192.168.16.41,192.168.16.42 "
CMD bash /root/init.sh $parameter

